# Generated by Django 4.0.6 on 2022-11-05 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'Negative Group O'), ('O+', 'Positive Group O'), ('A-', 'Negative Group A'), ('A+', 'Positive Group A'), ('B-', 'Negative Group B'), ('B+', 'Positive Group B'), ('AB-', 'Negative Group AB'), ('AB+', 'Positive Group AB')], default='O+', max_length=3, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='iin',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='IIN numer'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle Name'),
        ),
    ]
