# Generated by Django 4.0.6 on 2022-11-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_number',
        ),
    ]
