# Generated by Django 4.0.6 on 2022-11-05 23:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_emergency_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='KZ'),
        ),
    ]
