# Generated by Django 4.0.6 on 2022-11-06 01:53

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_emergency_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='comments',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='KZ', verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], default='Single', max_length=15, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='O+', max_length=3, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='KZ', verbose_name='Emergency Contact Number'),
        ),
    ]
