# Generated by Django 4.0.6 on 2022-11-06 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_address_patient_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
