# Generated by Django 4.0.6 on 2022-11-06 13:12

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='IIN numer')),
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='ID number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', verbose_name='Contact Number')),
                ('department_id', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Department Number')),
                ('specializtion_id', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Specialization Number')),
                ('experience_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Rating')),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule_detials', models.TextField()),
                ('degree', models.CharField(choices=[('none', 'none'), ('associate', 'associate'), ('bachelor’s', 'bachelor’s'), ('graduate', 'graduate'), ('doctorate', 'doctorate'), ('professional', 'professional')], default='none', max_length=20, verbose_name='Degree Type')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('address', models.CharField(blank=True, max_length=256)),
                ('homepage_url', models.URLField(blank=True)),
            ],
        ),
    ]
