# Generated by Django 4.0.6 on 2022-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule_detials',
            field=models.TextField(blank=True),
        ),
    ]
